networks:
  project-network:
    driver: bridge

services:
  postgres:
    container_name: postgres
    networks:
      - project-network
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=projects
    ports:
      - 6600:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    container_name: redis
    networks:
      - project-network
    image: redis:latest
    restart: always
    ports:
      - '6399:6379'
    volumes: 
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
    driver: local
