[build.environment]
  NODE_VERSION = "18.12.0"
  PNPM_FLAGS = "--shamefully-hoist"

[build]
  base = "apps/nuxt-schema-tester"
  publish = "apps/nuxt-schema-tester/dist"
  command = "npx pnpm install --store=node_modules/.pnpm-store --frozen-lockfile && npx pnpm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
