# apps/marketing-website netlify.toml

[build.environment]
  NODE_VERSION = "18.12.0"
  PNPM_FLAGS = "--shamefully-hoist"

[build]
  base = "apps/marketing-website"
  publish = "apps/marketing-website/dist"
  command = "pnpm install --store=node_modules/.pnpm-store --frozen-lockfile && pnpm build"

  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ."

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
