import type { Prisma } from '../../dist'

export const basicHomeObedience: Prisma.CourseCreateInput = {
  title: 'Basic Home Obedience',
  description: 'This is your opportunity to provide strong foundation which will serve you and your dog well for many years. We focus on developing strong obedience skills for you dog and address most common behaviour issues.',
  status: 'ACTIVE',
  slug: 'basic-home-obedience',
  categories: {
    connect: { slug: 'adult-dog-basic-obedience' },
  },
  classes: {
    create: [
      {
        title: 'Basic Home Obedience 1',
        description: 'We focus on developing strong obedience skills for you dog and address most common behaviour issues. Intended for dogs that older than 6 months old with little or no training.',
        price: { amount: '1250', period: '/dog', symbol: 'R' },
        duration: '10 weeks',
        audience: 'Beginner dogs that are 6 months +',
        features: [
          'Basic obedience, mental stimulation, enrichment and tricks',
          'Leash and heel work',
          'Jumping and common behaviour problems',
          'Behaviour shaping and behaviour modification',
          'Poison proofing',
          'Entry level socialization',
          'Handler coping skills',
          'Marker words',
          'Building the bond between handler and dog',
          'Custom advice based on dog psychology',
          'Sounds, textures and environmental desensitization',
          'Poison proofing',
          'Impulse control',
        ],
        mostPopular: false,
        status: 'ACTIVE',
        slug: 'basic-home-obedience-1',
      },
      {
        title: 'Basic Home Obedience 2',
        description: 'After graduating Home Obedience One, you and your dog can focus on further development and mastering consistent behaviours to a level suitable for solving real-world problems.',
        price: { amount: '1500', period: '/dog', symbol: 'R' },
        duration: '10 weeks',
        audience: 'Requirement completion of BHO1',
        features: [
          'Includes all of Basic Home Obedience One',
          'Basic obedience, mental stimulation, enrichment and tricks',
          'Leash and heel work',
          'Jumping and common behaviour problems',
          'Behaviour shaping and behaviour modification',
          'Poison proofing',
          'Entry level socialization',
          'Handler coping skills',
          'Marker words',
          'Building the bond between handler and dog',
          'Custom advice based on dog psychology',
          'Sounds, textures and environmental desensitization',
          'Poison proofing',
          'Impulse control',
        ],
        mostPopular: false,
        status: 'ACTIVE',
        slug: 'basic-home-obedience-2',
      },
      {
        title: 'Basic Home Obedience 3',
        description: 'This is where we start developing the necessary skills to continue onto our intermediate obedience courses. Here we will help you develop distance control, verbal and non-verbal commands ',
        price: { amount: '385', period: '/dog', symbol: 'R' },
        duration: '8 to 12 weeks',
        audience: 'Requirement completion of BHO2 or Puppy 2',
        features: [
          'Includes all of Basic Home Obedience Two',
          'Basic obedience, mental stimulation, enrichment and tricks',
          'Leash and heel work',
          'Jumping and common behaviour problems',
          'Behaviour shaping and behaviour modification',
          'Poison proofing',
          'Entry level socialization',
          'Handler coping skills',
          'Marker words',
          'Building the bond between handler and dog',
          'Custom advice based on dog psychology',
          'Sounds, textures and environmental desensitization',
          'Poison proofing',
          'Impulse control',
        ],
        mostPopular: false,
        status: 'ACTIVE',
        slug: 'basic-home-obedience-3',
      },
    ],
  },
}
